name: Super Lint
on: [push]
jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
    - uses: actions/checkout@v2
    - name: super lint
      uses: github/super-linter@v3
